[package]
name = "rascii_art"
version = "0.2.0"
authors = [ "KoBruhh", "RGBCube" ]
description = "Advanced ASCII Art Generator"
repository = "https://github.com/KoBruhh/RASCII"
keywords = [ "ascii" ]
license = "MIT"
edition = "2021"

[dependencies]
image = "0.24"

[[bin]]
name = "rascii"
