[package]
name = "rascii_art"
version = "0.2.61"
authors = [ "KoBruhh", "RGBCube" ]
description = "Advanced ASCII Art Generator"
repository = "https://github.com/KoBruhh/RASCII"
keywords = [ "ascii" ]
license = "MIT"
edition = "2021"

[dependencies]
 clap = { version = "4.3.0", features = [ "derive" ] }
image = "0.24.6"
termcolor = "1.2.0"

[build]
incremental = true

[[bin]]
name = "rascii"
path = "src/main.rs"
